name: "Check that all POEditor Terms are translated"

on:
  workflow_call:
    inputs:
      poeditor_project:
        type: string
        required: true
    secrets:
      poeditor_api_key:
        required: true

jobs:
  build:
    name: "Check translations"
    runs-on: ubuntu-latest
    steps:
      - name: Check translation percentage
        id: check_translation_status
        run: |
          RESP=$(curl --location 'https://api.poeditor.com/v2/languages/list' --silent --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' --data-urlencode 'api_token=${{secrets.poeditor_api_key}}' --data-urlencode 'id=${{inputs.poeditor_project}}')
          RESULT=$(echo $RESP | jq -r '.result.languages | map(select(.percentage < 100)) | map(.name) | join("|")')
          
          echo "CHECK_RESULT=${RESULT}" >> $GITHUB_OUTPUT
          if [[ $RESULT != "" ]]; then
            exit 1
          fi
        continue-on-error: true

      - uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const input = "${{ steps.check_translation_status.outputs.CHECK_RESULT }}"
            const languages = input.split('|');
            let text = "";
            if(input == "") {
              text = `All languages are fully translated`;
            } else {
              text = `The following languages are not fully translated:`;
              languages.forEach(function(language) {
                text += `\n- ${language}`;
              });
            }

            const output = `#### Translations Check Result 🗣️ \`${{ steps.check_translation_status.outcome }}\`

            ${text}
            
            *Pushed by: @${{ github.actor }}*`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Translations Check Status
        if: steps.check_translation_status.outcome == 'failure'
        run: exit 1