on:
  workflow_call:

jobs:
  update-release-draft:
    name: updating draft
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  autolabel:
    name: autolabel
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter/autolabeler@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
