name: "Setup node AWS Env"

on:
  workflow_call:
    inputs:
      path:
        type: string
        required: false
        default: ./node-aws-env
    secrets:
      hb_github_token:
        required: true

jobs:
  build:
    name: "Checkout"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout node-aws-env
        uses: actions/checkout@v5
        with:
          repository: understory-io/node-aws-env
          ref: feature/cmd-line-args
          path: ${{ inputs.path }}
          token: ${{ secrets.hb_github_token }}

      - name: Install
        run: |
          cd ${{ inputs.path }}
          npm install
